trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseYuniqlCLI@0
  inputs:
    version: 'latest'

- task: RunYuniqlCLI@0
  inputs:
    version: 'latest'
    connectionString: 'Server=tcp:paspostsql.postgres.database.azure.com,1433;Initial Catalog=helloyuniql;User ID=Selhhost@paspostsql;Password=Welcome5005@;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    workspacePath: '$(Build.SourcesDirectory)\samples\basic-postgresql-sample'
    targetPlatform: 'PostgreSql'
    additionalArguments: '--debug'