trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/rdagumampan/yuniql $(Build.SourcesDirectory)\yuniql'
- task: UseYuniqlCLI@1
  inputs:
    version: 'v1.1.55'
  
- task: RunYuniqlCLI@1
  inputs:
    version: 'v1.1.55'
    connectionString: 'Server=welcome.postgres.database.azure.com;Port=5432;Database=newdatabase;User Id=welcome;Password=Microsoft5005@;'
    workspacePath: '$(Build.SourcesDirectory)\samples\basic-postgresql-sample'
    targetPlatform: 'postgresql'
    additionalArguments: '--debug'