trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: UseYuniqlCLI@1
  inputs:
    version: 'latest'

- task: RunYuniqlCLI@1
  inputs:
    version: 'v0.00'
    connectionString: 'Server=tcp:paspostsql.postgres.database.azure.com,5432;Initial Catalog=helloyuniql;User ID=Selhhost@paspostsql;Password=Welcome5005@;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    workspacePath: '$(Build.SourcesDirectory)\samples\basic-postgresql-sample'
    targetPlatform: 'PostgreSql'
    additionalArguments: '--debug'