trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/dinesh-0723/yuniql  $(Build.SourcesDirectory)\yuniql'
- task: UseYuniqlCLI@1
  inputs:
    version: 'v1.1.55'
  
- task: RunYuniqlCLI@1
  inputs:
    version: 'v1.1.55'
    connectionString: 'Server=148.64.7.83;Port=5432;Database=postgres;User Id=welcome;Password=Azure5005@;'
    workspacePath: '$(Build.SourcesDirectory)/samples/basic-postgresql-sample'
    targetPlatform: 'postgresql'
    additationalArguments: '--debug'